name: BuiltIn Variables Demo
run-name: ${{ github.actor }} is testing out BuiltIn Variables Demo
on:
  workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: echo "The job was automatically triggered by a ${{ github.even_name }} event."
    - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "This name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v4
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner. "
    - name: List files in the repository
      run: |
         ls ${{ github.workspace }}
    - run: echo "This job's status is ${{ job.status }}. "
    
